apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
      include: '*.yaml'
    repoURL: https://github.com/elvis-cai/xplane-tenant-project.git 
    targetRevision: HEAD
    path: crossplane-resources
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
      - CreateNamespace=true
