apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: crossplane
    helm:
      releaseName: crossplane
      values: |
        args:
         - --debug
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.12.2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
      - CreateNamespace=true
